### ISSUE TITLE
Redmine 4.1.1 - Edit issue hiding, view issue not hiding

### ISSUE THREAD

**Issue by andreav** [nanego/redmine_customize_core_fields#14]
Hello,
thank you for this plugin.

I was using it in Redmine 3.6 and everything worked ok.

Now I upgraded to Redmine 4.1.1 and I have this problem:

- Edit issue correctly hides the field
- However when the user views the issue, she sees the hidden field.

My setup:

- Redmine version: 4.1.1.stable
- Redmine Base Deface plugin: 1.5.3
- Redmine Customize Core Fields plugin: master

I tried removing all plugins but the behaviour is the same.

Thank you.

**Comment by andreav** [comment]
Sorry for wasting your time, I finally found my mistake.

 I need to enable "Core fields visibility" module at project level.

Thank you again for this plugin.

**Comment by EchedelleLR** [comment]
@andreav I think that this issue is still maintained even with "Core fields visibility enabled".

It doesn't seem to work correctly with the "Status" field.
