### ISSUE TITLE
Unexpected return

### ISSUE THREAD

**Issue by mcortellino** [nanego/redmine_customize_core_fields#15]
I have installed this plugin on Redmine 4.1.1 I got an "unexpected return" error on line 17 of /plugins/redmine_customize_core_fields/app/models/core_field.rb

after commenting this line out the plugins seems to work as expected.

**Comment by nanego** [comment]
Can you please provide more details? In which context the error happened? is the user admin? 
Are you using any other plugin?

**Comment by mcortellino** [comment]
The error appears navigating in /settings page

this is the list of installed plugins:


https://github.com/jbbarth/redmine_base_deface
http://github.com/a-ono/redmine_ckeditor
https://github.com/nanego/redmine_customize_core_fields
https://github.com/return1/redmine_hide_estimated_hours

**Comment by codelabstudio** [comment]
I fixed the issue with this modification on file core_field.rb

```diff
17c17
<     return none if user.admin? or (project.present? and !project.module_enabled?("customize_core_fields"))
---
>    
29a30,31
>     user ||= User.current
>     return none if user.admin? or (project.present? and !project.module_enabled?("customize_core_fields"))	
```

**Comment by nanego** [comment]
The issue has been resolved some time ago with this fix. Thanks
