### ISSUE TITLE
Redmine 5

### ISSUE THREAD

**Issue by kroxy** [nanego/redmine_customize_core_fields#16]
Hi, I have redmine 5 instalation and I need this plugin. I tried this plugin instalation but dosent work. Can you actualition in redmine 5 too? thanx

**Comment by perryjun** [comment]
> 嗨，我有 redmine 5 安装，我需要这个插件。我尝试了这个插件安装，但效果不佳。你也可以在redmine 5中实现吗？谢谢

me too，the same request

**Comment by Bonerserk** [comment]
Yes, will be very usefull. I'm waiting this plugin to upgrade to redmine 5.
Thanks

**Comment by nanego** [comment]
Hello
I have just updated the plugin. It should work with Redmine 5.
Can you try the latest version?

**Comment by Bonerserk** [comment]
Many thanks.
I tried with a clean installation of redmine version 5.0.2 and 5.0.4 based both on Alpine and Bullseye
I installed latest version with success of redmine_base_deface.
But I always have this error and redmine doesn't start

"
Your Gemfile lists the gem puma (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
The Gemfile's dependencies are satisfied
=> Booting Puma
=> Rails 6.1.6 application starting in production 
=> Run `bin/rails server --help` for more startup options
W, [2022-12-05T11:33:13.867486 #1]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2022-12-05T11:33:14.084439 #1]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2022-12-05T11:33:14.273773 #1]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
Exiting
/usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get': uninitialized constant RedmineCustomizeCoreFields::IssuePatch (NameError)
    parent.const_get(cname, false)
          ^^^^^^^^^^
Did you mean?  IssueImport
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:234:in `block in eager_load'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `synchronize'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `eager_load'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `each'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `eager_load_all'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
	from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
	from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:39:in `start'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:135:in `perform'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/command.rb:48:in `invoke'
	from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
"
My Redmine environment:

Environment:
  Redmine version                5.0.4.stable
  Ruby version                   3.1.3-p185 (2022-11-24) [x86_64-linux]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.14.1
  Mercurial                      5.6.1
  Bazaar                         3.1.0
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  redmine_base_deface            1.6.2

Thanks

**Comment by nanego** [comment]
Those errors were only happening in production mode, with Zeitwerk autoloading.
It should be fixed in the latest version.

**Comment by Bonerserk** [comment]
Thanks @nanego your last release worked well on redmine 5!

**Comment by perryjun** [comment]
can be installed, but not work，redmine5.0

**Comment by nanego** [comment]
The plugin has been updated for Redmine 5.1.1
