### ISSUE TITLE
"Status" field gives error in modification because the field id is not set correctly

### ISSUE THREAD

**Issue by EchedelleLR** [nanego/redmine_customize_core_fields#17]
I attach a picture where I show an example of the problem and a way to fix it by resending the request with the correct field id, which is, surprisingly, correctly set when I go to edit the field visibility.

![2022-08-05_09-07_1](https://user-images.githubusercontent.com/56733813/183049635-7727f5b1-6304-4bd2-b361-facb4ddbebd3.png)

The Redmine version is 4.2.7.

**Comment by EchedelleLR** [comment]
Possibly related with the behavior of this field: [#14#issuecomment-1206260920](https://github.com/nanego/redmine_customize_core_fields/issues/14#issuecomment-1206260920)

**Comment by nanego** [comment]
Hello.
I have just addressed the problem with the status field.
Please get the last version of the plugin and confirm that everything is working now.
Have a great day!

**Comment by EchedelleLR** [comment]
Sorry for my delay, I confirm tomorrow.

**Comment by EchedelleLR** [comment]
I can confirm.
