### ISSUE TITLE
when I installed the plugin,I got an error as blow.

### ISSUE THREAD

**Issue by liwenchao-sh** [nanego/redmine_customize_core_fields#2]
C:\BitNami\redmine-3.2.1-0\apps\redmine\htdocs\plugins>rake redmine:plugins:migrate RAILS_ENV=production --trace
(in C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs)
DL is deprecated, please use Fiddle
*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:123:in `find'
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:251:in`requires_redmine_plugin'
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/plugins/redmine_customize_core_fields/init.rb:8:in `block in <top (required)>'
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:75:in`instance_eval'
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:75:in `register'
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/plugins/redmine_customize_core_fields/init.rb:1:in`<top (required)>'
C:/BitNami/redmine-3.2.1-0/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
C:/BitNami/redmine-3.2.1-0/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`block in require'
C:/BitNami/redmine-3.2.1-0/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
C:/BitNami/redmine-3.2.1-0/ruby/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`require'
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in `block in load'
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in`each'
C:/BitNami/redmine-3.2.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `load'
.....

C:/BitNami/redmine-3.2.1-0/ruby/bin/rake:23:in `load':/BitNami/redmine-3.2.1-0/ruby/bin/rake:23:in`<main>'
Tasks: TOP => redmine:plugins:migrate => environment

---

My redmine is vesion 3.2.
Any suggestion may solve this problem?

**Comment by nanego** [comment]
I have removed a dependence to the redmine_deface plugin, which was not useful.
You should now be able to run this plugin without having to install any other resource.

**Comment by liwenchao-sh** [comment]
3Q so much.
I've got this plugin installed.
