### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by MattRogowski** [nanego/redmine_customize_core_fields#3]
Hello,

We have installed and we are getting a syntax error as follows:

`/usr/share/redmine/plugins/redmine_customize_core_fields/lib/redmine_customize_core_fields/hooks.rb:6: syntax error, unexpected ':', expecting ')' ...tag('core_fields.css', plugin: 'redmine_customize_core_field... ^ /usr/share/redmine/plugins/redmine_customize_core_fields/lib/redmine_customize_core_fields/hooks.rb:6: syntax error, unexpected ')', expecting kEND`

Our installation info:

```
Environment:
  Redmine version                2.3.3.stable.12240
  Ruby version                   1.8.7-p352 (2011-06-30) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               MySQL
```

**Comment by nanego** [comment]
Hello
This plugin should work well on Redmine 2.3.3, but it is **not** compatible with Ruby 1.8.7.
If you cannot update your Redmine application, you should at least move to a newer version of Ruby. Redmine 2.3.3 works very well with Ruby 1.9.x or Ruby 2.0.x.

**Comment by MattRogowski** [comment]
Thank you, after much hassle I've now updated Ruby, however I'm now getting a new error:

```
# /usr/bin/rake1.9.1 redmine:plugins RAILS_ENV=production
(in /usr/share/redmine)
svn: warning: cannot set LC_CTYPE locale
svn: warning: environment variable LANG is en_GB.UTF-8
svn: warning: please check that your locale name is correct
rake aborted!
Redmine::PluginNotFound

Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

The plugin has been cloned into `/plugins` into a directory called `redmine_customize_core_fields` as per the docs, so I'm not sure why it can't find it? If I remove the folder, it works fine, so it is something specific to this plugin being there.

**Comment by nanego** [comment]
Actually, I have recently added a dependence to another plugin: https://github.com/jbbarth/redmine_base_deface
You will have to install it.

I will complete the Readme with a quick note about it.
