### ISSUE TITLE
Custome fields visualized before Standard fields

### ISSUE THREAD

**Issue by andreav** [nanego/redmine_customize_core_fields#8]
Hello, thank you for this plugin it work like a charm.

Just one question: when I add custom fields to any tracker, and go to "new issue" tab, they appear before standard fields.

Can this be changed/configured to restore redmine original behaviour, i.e. first standard fields, then custom fields?

Thank you.

**Comment by nanego** [comment]
Hello.
Yes, currently, if you select "customize issue form" in the plugin settings, custom fields appear first.
I will plan to update the plugin and make it possible to choose the order.

**Comment by andreav** [comment]
Great! Thank you!

**Comment by nanego** [comment]
I have updated the plugin and added a new parameter in settings.
Please have a look at this new option and tell me if everything works fine.
Thanks

**Comment by andreav** [comment]
Wow super fast response, thank you.

I installed new version, migrate plugin and restarted redmine.

Now Under "configure plugin" I see a new customization entry
However If I choose "No", custom fields are still rendered first in form.

Should I have to do something more?

![image](https://user-images.githubusercontent.com/1358304/47500482-348fc780-d863-11e8-954f-3435e1efd185.png)

**Comment by nanego** [comment]
Can you tell me what is your browser version? With these settings, it should work.

**Comment by andreav** [comment]
Sorry, I'm sure it was not working before.
I just retried and it works perfectly!

Thank you!
